include:
  - definitions/critical.yml
  - definitions/figbert.yml
  - definitions/services.yml
  - definitions/automation.yml

services:
  ingress:
    image: caddy:alpine
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    depends_on:
      - homepage
      - scroll
      - blinddateabook
      - systemcolors
      - miniflux
      - bitwarden
      - radicale
      - owncast
      - linkding
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./services/caddy:/data/caddy
